compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules

npmScopes:
  mijohen:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"