name: Publish Packages

on: pull_request

jobs:
  publish:
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: corepack enable
        - run: yarn run setup
        - run: yarn run prep
        - run: yarn run publish
